app:
  serviceName: app
  image: franzramadhan/backend:latest
  imagePullPolicy: Always
  minReplicas: 1
  maxReplicas: 10
  targetCpuUtilization: 80
  servicePort: 8080
  resources: 
    limits:
      cpu: 256m
      memory: 512Mi
    requests:
      cpu: 128m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10
  restartPolicy: Always

db:
  serviceName: db
  image: mysql:8
  imagePullPolicy: IfNotPresent
  servicePort: 3306
  resources: 
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 250m
      memory: 64Mi
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 15
  restartPolicy: Always
