apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.serviceName }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.serviceName }}-deployment
  minReplicas: {{ .Values.app.minReplicas }}
  maxReplicas: {{ .Values.app.maxReplicas }}
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: app
        target:
          type: Utilization
          averageUtilization: {{ .Values.app.targetCpuUtilization }}
